---
sidebar: sidebar 
permalink: use/cache-manage.html 
keywords: volume caching, Volume caching 
summary: 볼륨 캐싱은 원격 장소에 지속적이고 쓰기 가능한 볼륨을 제공합니다.  볼륨 캐싱을 사용하면 데이터 액세스 속도를 높이거나 액세스 빈도가 높은 볼륨의 트래픽을 오프로드할 수 있습니다.  캐시 볼륨은 읽기 작업이 많은 작업, 특히 클라이언트가 동일한 데이터에 반복적으로 액세스해야 하는 경우에 이상적입니다. 
---
= 캐시 관리
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
캐시를 편집하고, 내보내기 정책을 변경하고, 캐시 크기를 조정하고, 캐시를 삭제할 수 있습니다.

볼륨 캐싱을 사용하면 다음과 같은 목표를 달성할 수 있습니다.

* 캐시 세부 정보를 확인하세요.
* 캐시에 다른 내보내기 정책을 할당합니다.
* 볼륨 캐싱을 편집하고 크기 등을 변경합니다. 편집에서는 다른 속성을 보고 변경할 수 있는 옵션이 제공되며, 향후 릴리스에서는 편집에 더 많은 속성이 추가될 예정입니다.
* 원래 볼륨 크기의 백분율을 기준으로 기존 캐시의 크기를 조정합니다.
* 캐시를 삭제합니다.




== 캐시 세부 정보 보기

각 캐싱에 대해 원래 볼륨, 작업 환경, 캐시 볼륨 등을 볼 수 있습니다.

.단계
. NetApp 콘솔 왼쪽 탐색에서 *모빌리티* > *볼륨 캐싱*을 선택합니다.
+
대상 시스템에 생성된 캐시 볼륨 목록을 볼 수 있습니다.  캐시 목록에는 캐시 세부 정보가 표시됩니다.

. 목록을 필터링하려면 *필터 기준 +* 옵션을 선택하세요.
. 행을 선택하고 오른쪽에 있는 *작업…* 옵션을 선택하세요.
. *세부정보 보기 및 편집*을 선택하세요.
. 자세한 내용을 검토하세요.




== 캐시 편집

캐시의 이름, 볼륨 크기 및 내보내기 정책을 변경할 수 있습니다.

.단계
. NetApp 콘솔 왼쪽 탐색에서 *모빌리티* > *볼륨 캐싱*을 선택합니다.
. 행을 선택하고 오른쪽에 있는 *작업…* 옵션을 선택하세요.
. *세부정보 보기 및 편집*을 선택하세요.
. 기본 구성 탭에서 원하는 경우 캐시 이름과 캐시 볼륨 크기를 변경합니다.
. 선택적으로 캐시 액세스 탭을 확장하고 다음 값을 수정합니다.
+
.. 마운트 경로.
.. 기존과 다른 수출 정책.


. SMB/CIFS 공유 세부 정보나 내보내기 정책 규칙을 변경하려면 해당 옵션을 클릭하여 NetApp System Manager에 액세스하세요.
. *저장*을 선택하세요.




== 다른 캐시 내보내기 정책 할당

캐시에 다른 내보내기 정책을 할당할 수 있습니다.

소스 내보내기 정책 규칙은 대상 클러스터에 적용되어야 합니다.


TIP: 기존 내보내기 정책을 캐시에 할당할 수 있습니다.  수출 정책 규칙을 변경할 수 없습니다.  내보내기 정책을 변경해야 하는 경우 NetApp System Manager를 사용할 수 있습니다.

.단계
. NetApp 콘솔 왼쪽 탐색에서 *모빌리티* > *볼륨 캐싱*을 선택합니다.
. 행을 선택하고 오른쪽에 있는 *작업…* 옵션을 선택하세요.
. *수출 정책 변경*을 선택합니다.
. 캐시에 할당할 내보내기 정책을 선택하세요.
. *저장*을 선택하세요.




== 캐시 크기 조정

소스 볼륨의 백분율에 따라 캐시 볼륨의 크기를 변경할 수 있습니다.

.단계
. NetApp 콘솔 왼쪽 탐색에서 *모빌리티* > *볼륨 캐싱*을 선택합니다.
. 행을 선택하고 오른쪽에 있는 *작업…* 옵션을 선택하세요.
. *크기 조정*을 선택하세요.
. 원본 볼륨 크기의 새로운 백분율을 입력하세요.
+
캐시 볼륨은 새로운 백분율로 크기가 조정됩니다.

. *저장*을 선택하세요.




== 캐시 삭제

캐시가 더 이상 필요하지 않으면 삭제할 수 있습니다.  이렇게 하면 볼륨 캐싱 관계가 삭제되고 대상 볼륨 캐시가 삭제됩니다.

.단계
. NetApp 콘솔 왼쪽 탐색에서 *모빌리티* > *볼륨 캐싱*을 선택합니다.
. 행을 선택하고 오른쪽에 있는 *작업…* 옵션을 선택하세요.
. *삭제*를 선택하세요.
. 상자를 체크하세요.
. *삭제*를 선택하세요.

