---
sidebar: sidebar 
permalink: get-started/cache-intro.html 
keywords: how volume caching works, what is volume caching, bluexp 
summary: 볼륨 캐싱은 원격 장소에 지속적이고 쓰기 가능한 볼륨을 제공합니다.  볼륨 캐싱을 사용하면 데이터 액세스 속도를 높이거나 액세스 빈도가 높은 볼륨의 트래픽을 오프로드할 수 있습니다.  캐시 볼륨은 읽기 작업이 많은 작업, 특히 클라이언트가 동일한 데이터에 반복적으로 액세스해야 하는 경우에 이상적입니다. 
---
= 볼륨 캐싱에 대해 알아보세요
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9 소프트웨어의 기능인 볼륨 캐싱은 파일 배포를 간소화하고, 리소스를 사용자와 컴퓨팅 리소스가 있는 곳에 더 가깝게 배치하여 WAN 지연 시간을 줄이고, WAN 대역폭 비용을 낮추는 원격 캐싱 기능입니다.  볼륨 캐싱은 원격 장소에 지속적이고 쓰기 가능한 볼륨을 제공합니다.  볼륨 캐싱을 사용하면 데이터 액세스 속도를 높이거나 액세스 빈도가 높은 볼륨의 트래픽을 오프로드할 수 있습니다.  캐시 볼륨은 읽기 작업이 많은 작업, 특히 클라이언트가 동일한 데이터에 반복적으로 액세스해야 하는 경우에 이상적입니다.

볼륨 캐싱을 사용하면 클라우드, 특히 Amazon FSx for NetApp ONTAP, Cloud Volumes ONTAP 및 온프레미스 작업 환경에서 캐싱 기능을 사용할 수 있습니다.

볼륨 캐싱은 지점 사무실에서 회사 데이터 세트에 액세스할 수 있도록 해줍니다.  클러스터 내 여러 컨트롤러에서 자주 액세스해야 하는 데이터인 _핫 데이터_를 제공하면 주요 애플리케이션에 제공되는 성능을 높일 수 있습니다.  또한 전 세계 여러 지역의 사용자에게 핫 데이터를 로컬로 캐싱하면 중앙 집중식 데이터 세트에 동시에 액세스할 수 있어 협업을 강화할 수 있으며, 핫 데이터에 액세스할 때 받는 응답 시간도 줄일 수 있습니다.



== NetApp 콘솔

볼륨 캐싱은 NetApp 콘솔을 통해 액세스할 수 있습니다.

NetApp 콘솔은 엔터프라이즈급 온프레미스 및 클라우드 환경 전반에서 NetApp 스토리지 및 데이터 서비스를 중앙에서 관리할 수 있는 기능을 제공합니다. NetApp 데이터 서비스에 액세스하고 사용하려면 콘솔이 필요합니다. 관리 인터페이스로서, 하나의 인터페이스에서 여러 스토리지 리소스를 관리할 수 있습니다. 콘솔 관리자는 기업 내 모든 시스템의 저장소와 서비스에 대한 액세스를 제어할 수 있습니다.

NetApp Console을 사용하려면 라이선스나 구독이 필요하지 않으며, 스토리지 시스템이나 NetApp 데이터 서비스에 대한 연결을 보장하기 위해 클라우드에 Console 에이전트를 배포해야 할 때만 요금이 부과됩니다. 그러나 콘솔에서 액세스할 수 있는 일부 NetApp 데이터 서비스는 라이선스 기반이거나 구독 기반입니다.

자세히 알아보세요 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html["NetApp 콘솔"] .



== 캐시란 무엇인가요?

캐시는 호스트와 데이터 소스 사이에 있는 임시 저장 위치입니다.  캐시의 목적은 소스 데이터 중 자주 액세스되는 부분을 저장하는 방식으로, 소스에서 데이터를 가져오는 것보다 더 빠르게 데이터를 제공할 수 있도록 하는 것입니다.  캐시는 여러 호스트에서 데이터에 두 번 이상 액세스하고 공유하는 읽기 중심 환경에서 가장 유용합니다.  캐시 시스템은 데이터 소스가 있는 시스템보다 빠른데, 이는 더 빠른 저장 시스템과 캐시 저장 공간이 호스트와 가까운 것을 통해 달성됩니다.



== 볼륨 캐싱의 이점

볼륨 캐싱은 다음과 같은 이점을 제공합니다.

* 하이브리드 클라우드 인프라에서 성능 가속화
* 한 클라우드 공급자의 데이터를 다른 클라우드 공급자에게 캐싱하여 클라우드 사일로를 제거합니다.
* 낮은 보관 비용
* 여러 지리적 위치에서 협업
* 변화하는 IT 환경에 더 빠르게 적응할 수 있는 능력
* 클라우드에서 호스팅되는 주문형 또는 구독 기반 볼륨 캐싱




== 볼륨 캐싱으로 할 수 있는 일

볼륨 캐싱을 사용하면 다음과 같은 목표를 달성하기 위해 여러 NetApp 기술을 최대한 활용할 수 있습니다.

* 한 클라우드 공급자에서 다른 공급자로 캐시 데이터 전송
* 캐시 내보내기 정책 보기 및 편집
* 기존 캐시 크기 조정
* 캐시 삭제




== 비용

NetApp 볼륨 캐싱에 대해 요금을 청구하지 않지만, 적용되는 데이터 유입 및 유출 요금에 대해서는 클라우드 공급업체를 확인해야 합니다.



== 라이센스

볼륨 캐싱에는 특별한 ONTAP 라이선스가 필요하지 않습니다.



== 볼륨 캐싱 작동 방식

캐시 볼륨은 소스 볼륨에 의해 백업되는, 밀도가 낮은 볼륨입니다.  캐시 볼륨은 소스 볼륨과 동일한 클러스터에 있을 수도 있고 다른 클러스터에 있을 수도 있습니다.

캐시 볼륨은 모든 데이터가 캐시 볼륨에 있을 필요 없이 소스 볼륨의 데이터에 액세스할 수 있도록 해줍니다.  캐싱 볼륨의 데이터 저장은 핫 데이터(작업 데이터 또는 최근에 사용된 데이터)만 보존함으로써 효율적으로 관리됩니다.

볼륨 캐싱은 캐시 볼륨에 클라이언트가 요청한 데이터가 포함되어 있는 경우 요청을 읽습니다.  그렇지 않은 경우, 볼륨 캐싱 서비스는 소스 볼륨에서 데이터를 요청하고 클라이언트 요청을 처리하기 전에 데이터를 저장합니다.  이후의 데이터 요청은 캐시 볼륨에서 직접 처리됩니다.  이렇게 하면 동일한 데이터에 반복적으로 액세스할 때 성능이 향상됩니다. 첫 번째 요청 이후에는 데이터가 더 이상 네트워크를 통해 이동하거나 과부하된 시스템에서 제공될 필요가 없기 때문입니다.
