---
sidebar: sidebar 
permalink: release-notes/cache-whats-new.html 
keywords: volume caching faq, bluexp, volume caching frequently asked questions 
summary: 볼륨 캐싱은 원격 장소에 지속적이고 쓰기 가능한 볼륨을 제공합니다. 볼륨 캐싱을 사용하면 데이터 액세스 속도를 높이거나 액세스 빈도가 높은 볼륨의 트래픽을 오프로드할 수 있습니다. 캐시 볼륨은 읽기 작업이 많은 작업, 특히 클라이언트가 동일한 데이터에 반복적으로 액세스해야 하는 경우에 이상적입니다. 
---
= 볼륨 캐싱의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨 캐싱의 새로운 소식을 알아보세요.



== 2025년 10월 6일



=== BlueXP volume caching 이 이제 볼륨 캐싱입니다.

BlueXP volume caching 볼륨 캐싱으로 이름이 바뀌었습니다.

NetApp Console 왼쪽 탐색 모음에서 *모빌리티* > *볼륨 캐싱*을 선택하여 액세스할 수 있습니다.



=== BlueXP 는 이제 NetApp Console 입니다.

강화되고 재구성된 BlueXP 기반을 기반으로 구축된 NetApp Console 엔터프라이즈급 온프레미스 및 클라우드 환경에서 NetApp 스토리지와 NetApp Data Services 중앙에서 관리하여 실시간 통찰력, 더 빠른 워크플로, 간소화된 관리를 제공하며, 높은 보안성과 규정 준수를 보장합니다.

변경된 내용에 대한 자세한 내용은 다음을 참조하세요.link:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["NetApp Console 릴리스 노트"] .



== 2023년 6월 4일



=== BlueXP volume caching

ONTAP 9 소프트웨어의 기능인 BlueXP volume caching 파일 배포를 간소화하고, 리소스를 사용자와 컴퓨팅 리소스가 있는 곳에 더 가깝게 가져와 WAN 지연 시간을 줄이고, WAN 대역폭 비용을 낮추는 원격 캐싱 기능입니다. 볼륨 캐싱은 원격 장소에 지속적이고 쓰기 가능한 볼륨을 제공합니다. BlueXP volume caching 사용하면 데이터 액세스 속도를 높이거나 액세스가 많은 볼륨의 트래픽을 오프로드할 수 있습니다. 캐시 볼륨은 읽기 작업이 많은 작업, 특히 클라이언트가 동일한 데이터에 반복적으로 액세스해야 하는 경우에 이상적입니다.

BlueXP volume caching 사용하면 클라우드, 특히 Amazon FSx for NetApp ONTAP, Cloud Volumes ONTAP 및 온프레미스 작업 환경에서 캐싱 기능을 사용할 수 있습니다.

link:https://docs.netapp.com/us-en/bluexp-volume-caching/get-started/cache-intro.html["볼륨 캐싱에 대해 자세히 알아보세요"] .
